### ISSUE TITLE
1.21 Support?

### ISSUE THREAD

**Issue by ItsmagmaMan09** [DuncanRuns/Chunkumulator#5]

**Comment by DuncanRuns** [comment]
See https://github.com/DuncanRuns/Chunkumulator/issues/2

**Comment by ItsmagmaMan09** [comment]
i tried launching it on my server but it crashed, is there something I'm doing wrong?

`Starting net.fabricmc.loader.impl.game.minecraft.BundlerClassPathCapture
[13:54:12] [main/INFO]: Loading Minecraft 1.21 with Fabric Loader 0.15.11
[13:54:13] [main/WARN]: Mod resolution failed
[13:54:13] [main/INFO]: Immediate reason: [HARD_DEP_INCOMPATIBLE_PRESELECTED chunkumulator 1.0.3+MC1.20.1 {depends minecraft @ [~1.20.1]}, ROOT_FORCELOAD_SINGLE chunkumulator 1.0.3+MC1.20.1]
[13:54:13] [main/INFO]: Reason: [HARD_DEP chunkumulator 1.0.3+MC1.20.1 {depends minecraft @ [~1.20.1]}]
[13:54:13] [main/INFO]: SERVER environment disabled: [fabric-renderer-api-v1, fabric-model-loading-api-v1, fabric-keybindings-v0, fabric-renderer-registries-v1, fabric-client-tags-api-v1, fabric-sound-api-v1, fabric-rendering-v0, fabric-screen-api-v1, fabric-rendering-v1, fabric-key-binding-api-v1, fabric-renderer-indigo, fabric-blockrenderlayer-v1]
[13:54:13] [main/INFO]: Fix: add [], remove [], replace [[chunkumulator 1.0.3+MC1.20.1] -> add:chunkumulator 1 ([(-∞,∞)])]
[13:54:13] [main/ERROR]: Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
         - Replace mod 'Chunkumulator' (chunkumulator) 1.0.3+MC1.20.1 with any version that is compatible with:
                 - minecraft 1.21
More details:
         - Mod 'Chunkumulator' (chunkumulator) 1.0.3+MC1.20.1 requires any version between 1.20.1 (inclusive) and 1.21- (exclusive) of 'Minecraft' (minecraft), but only the wrong version is present: 1.21!
        at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:195) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146) ~[fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.15.11.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.15.11.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:1.0.1]`

**Comment by DuncanRuns** [comment]
Ok
Remove the mod
It is not needed past 1.20.1

**Comment by ItsmagmaMan09** [comment]
alr
